# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c99a615ad2cc1b1b514c2e537823090bf2e508013d40e83cb50208ae98aa1337e8814fa8da648980f358358e2e70092ff77970b9617bf65fd8f170eebff17c64

test:
  secret_key_base: c29d91846b070447f7b3168d3b927874d2beb32f082690dd9fcf7f5d9866331fee7e9549d956932120920af125729dfd898a81a21e9e31e4a76a75b25c4373dc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
